const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateClassReportPDF = (sessionData, staffInfo, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text('GestureIQ — Class Session Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Class: ${sessionData.title}`);
    doc.text(`Staff: ${staffInfo.name} | Institution: ${staffInfo.institution_name}`);
    doc.text(`Date: ${new Date(sessionData.conductedAt).toLocaleString()}`);
    doc.text(`Duration: ${sessionData.duration} minutes`);
    doc.text(`Total Students: ${sessionData.totalStudents}`);
    doc.text(`Mudras Covered: ${sessionData.mudrasCovered.join(', ')}`);
    doc.text(`Class Average Score: ${sessionData.classAverage.toFixed(2)}%`);

    doc.moveDown();
    doc.fontSize(16).text('Student Performance Table:', { underline: true });
    doc.moveDown(0.5);

    // Table Header
    const tableHeader = ['Name', 'Mudra', 'Attempts', 'Best Score', 'Status'];
    const columnWidths = [120, 100, 80, 80, 100];
    let startX = 50;
    let startY = doc.y;

    doc.fontSize(12).font('Helvetica-Bold');
    tableHeader.forEach((header, index) => {
      doc.text(header, startX, startY);
      startX += columnWidths[index];
    });

    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10);

    // Table Rows
    sessionData.studentReports.forEach(student => {
      student.mudraScores.forEach(mudra => {
        let currentY = doc.y;
        if (currentY > 700) {
          doc.addPage();
          currentY = 50;
        }

        const status = mudra.bestScore >= 75 ? 'Mastered' : 'Needs Practice';
        let rowX = 50;
        doc.text(student.studentName, rowX, currentY);
        rowX += columnWidths[0];
        doc.text(mudra.mudra, rowX, currentY);
        rowX += columnWidths[1];
        doc.text(mudra.attempts.toString(), rowX, currentY);
        rowX += columnWidths[2];
        doc.text(`${mudra.bestScore}%`, rowX, currentY);
        rowX += columnWidths[3];
        doc.text(status, rowX, currentY);
        doc.moveDown();
      });
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).text(`Generated by GestureIQ on ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.text('gestureiq.com', { align: 'center', link: 'https://gestureiq.com' });

    doc.end();

    stream.on('finish', () => {
      resolve(outputPath);
    });

    stream.on('error', (err) => {
      reject(err);
    });
  });
};

module.exports = { generateClassReportPDF };
